[package]
name = "tonlib-sys"
version = "0.1.0"
authors = ["Ivan Kalinin <i.kalinin@dexpa.io>"]
edition = "2018"

[dependencies]
ton_api = { git = "https://github.com/broxus/ton-labs-tl.git" }
thiserror = "1.0"

[build-dependencies]
cc = "1.0.62"
cmake = "0.1"
